### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-css-sass-intro-8dVLYn#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-css-sass-intro-8dVLYn/) and meets the following criteria:

- [x] All components in [this HTML](https://gist.github.com/egillespie/15433761e640077f93660b4555a3d88b) are styled using Sass
- [x] Use four colors from a [random color palette](https://coolors.co/) (just copy the hex values into your Sass file) and link to your palette in the HTML
- [x] Font sizes are all determined by one base font size variable, even in `input` and `textarea` elements
- [x] All text uses the same font family, even in `input` and `textarea` elements
- [x] Elements shaped like a box (`img`, `input[type="text"]`, `textarea`) have the same `border-radius`
- [x] At least one built-in Sass function is used to style a component
- [x] Variables are defined in their own Sass file
- [x] Sass files are saved in a `source` directory and CSS files are saved in a `compiled` directory
- [x] A source map for your component library is included in the project

**Comment by KatieMFritz** [comment]
Nice start! I especially like the way you used comments in `_variables.scss`. 😁 

Watch out for [typos](https://github.com/GriffinMartin/MI-449-SS17-740-css-sass-intro-8dVLYn/blob/master/source/scss/_variables.scss#L15)! 
```scss
$border-radius: 10px;;
```

### Spacing
When you don't put a line break between CSS statements, it makes it a little hard to read. Since the compiled CSS gets minified anyway, the extra space isn't a performance problem. If you want to group selectors, you can use comments to title your sections. 🍕 

### Style table
I don't see any particular styles on the `table` element, other than applying the font. 

Here's a challenge for you: Give the rows of the table alternating backgrounds colors (based on your color palette), like this:

<img src="https://react.rocks/images/converted/react-bootstrap-table.jpg" alt="striped table" width="300px">

**Comment by GriffinMartin** [comment]
@KatieMFritz I fixed it up! 🎉

**Comment by KatieMFritz** [comment]
Thanks! I'm still seeing that typo from the previous comment. Can you fix that?

Also, your table styles look great. 🔥 I see repeated parts of selectors though (`tbody tr`) - try Sass nesting with that!

**Comment by GriffinMartin** [comment]
@KatieMFritz  I fixed the typo, must not have saved it when I fixed it before 🐛 

I added the nesting too.

**Comment by egillespie** [comment]
Hi @GriffinMartin, Katie's out of town so I'm jumping in. I see that the typo is fixed, but I think the table striping is not working how you intended.

Here's what you have now:

```scss
tbody tr {
  :nth-child(odd) {
    background-color: lighten($primary-color, 30%)
  }
  :nth-child(even) {
    background-color: $tertiary-color;
  }
}
```

It looks like you are trying to use a different color for the even and odd _rows_ in your table, but without the `&` prefix on `:nth-child`, the styles are actually applied to the child elements instead of the parent.

Here's what I propose:

1. Add a `&` before each `:nth-child`.
2. If you meant to style the _columns_ of your table, wrap the `:nth-child` attributes with a `td` selector so it is very clear what your intended outcome should be.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🛩

**Comment by GriffinMartin** [comment]
Good call, I fixed it up! Thanks 😄  @egillespie

**Comment by egillespie** [comment]
Magnifico! :shipit:
